#!/usr/bin/env bash
# uninstall.sh — Remove osEngineer wiring from target project(s).
#
# Usage:
#   ./uninstall.sh <repo-path>              # Remove from a single repo
#   ./uninstall.sh --workbench [<path>]     # Remove from every .git repo under <path>
#   ./uninstall.sh --global                 # Remove global git hooks
#   ./uninstall.sh --all                    # All of the above
#
# Idempotent and safe. Only removes files/directories that osEngineer created.
# Asks before deleting planning directories or user-modified files.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERSION="$(cat "$SCRIPT_DIR/VERSION" 2>/dev/null || echo "0.0.0-dev")"

log() { printf '[osEngineer-uninstall] %s\n' "$*"; }
warn() { printf '[osEngineer-uninstall] WARNING: %s\n' "$*" >&2; }

# ── Helpers ────────────────────────────────────────────────────────────────

is_osengineer_hook() {
  local f="$1"
  [ -f "$f" ] && head -3 "$f" 2>/dev/null | grep -q 'osEngineer'
}

# ── Per-repo uninstall ─────────────────────────────────────────────────────

uninstall_repo() {
  local repo="$1"
  local repo_name
  repo_name="$(basename "$repo")"

  [ -d "$repo/.git" ] || { warn "$repo is not a git repo — skipping"; return 0; }

  log "── removing from $repo_name ──"

  # 1. Git hooks
  local ghooks="$repo/.git/hooks"
  if [ -d "$ghooks" ]; then
    for hook in commit-msg pre-commit post-commit; do
      local dst="$ghooks/$hook"
      if [ -f "$dst" ] && is_osengineer_hook "$dst"; then
        if [ -f "$dst.pre-osengineer" ]; then
          mv "$dst.pre-osengineer" "$dst"
          log "  · restored original $hook hook"
        else
          rm -f "$dst"
          log "  · removed $hook hook"
        fi
      fi
    done
  fi

  # 2. .osengineer/ directory
  if [ -d "$repo/.osengineer" ]; then
    local has_user_data=false
    # Anything beyond the default seeded files counts as user data
    if [ -n "$(find "$repo/.osengineer" -type f 2>/dev/null \
      | grep -v '/handoffs/\.gitkeep$' \
      | grep -v '/bypass-log\.jsonl$' \
      | grep -v '/state\.yml$' \
      | grep -v '/evolution-counter\.yml$' \
      | grep -v '/teams/' \
      | grep -v '/init-progress\.yml$' \
      | grep -v '/adr-catalog\.yml$' \
      | grep -v '/evolution-proposals/' \
      | grep -v '/evolution-rejections\.jsonl$' \
      | head -1)" ]; then
      has_user_data=true
    fi
    if [ "$has_user_data" = true ]; then
      read -r -p "[osEngineer-uninstall] $repo_name/.osengineer/ contains user data. Delete? [y/N] " response
      if [[ "$response" =~ ^[Yy]$ ]]; then
        rm -rf "$repo/.osengineer"
        log "  · .osengineer/ removed"
      else
        log "  · .osengineer/ kept (user declined)"
      fi
    else
      rm -rf "$repo/.osengineer"
      log "  · .osengineer/ removed"
    fi
  fi

  # 3. .claude/agents/ — remove osEngineer agent files
  if [ -d "$repo/.claude/agents" ]; then
    local removed=0
    for agent in "$SCRIPT_DIR"/agents/*.md; do
      local fname
      fname="$(basename "$agent")"
      if [ -f "$repo/.claude/agents/$fname" ]; then
        rm -f "$repo/.claude/agents/$fname"
        removed=$((removed + 1))
      fi
    done
    if [ $removed -gt 0 ]; then
      log "  · $removed agent files removed from .claude/agents/"
    fi
    rmdir "$repo/.claude/agents" 2>/dev/null || true
    rmdir "$repo/.claude" 2>/dev/null || true
  fi

  # 4. .claude/settings.json — revert osEngineer merge (inline Node)
  if [ -f "$repo/.claude/settings.json" ]; then
    local cfg="$repo/.claude/settings.json"
    node -e "
const fs = require('fs');
const path = process.argv[1];
let existing;
try { existing = JSON.parse(fs.readFileSync(path, 'utf8')); }
catch (e) { process.exit(0); }

function isOseEntry(entry) {
  if (!entry || !Array.isArray(entry.hooks)) return false;
  return entry.hooks.some(h => typeof h?.command === 'string' && h.command.includes('osEngineer-'));
}

for (const event of Object.keys(existing.hooks || {})) {
  existing.hooks[event] = (existing.hooks[event] || []).filter(e => !isOseEntry(e));
  if (existing.hooks[event].length === 0) delete existing.hooks[event];
}
if (Object.keys(existing.hooks || {}).length === 0) delete existing.hooks;

if (existing.statusLine?.command?.includes('osEngineer-statusline')) {
  delete existing.statusLine;
}

if (existing.env) {
  delete existing.env.OSENGINEER_HOME;
  delete existing.env.OSENGINEER_VERSION;
  if (Object.keys(existing.env).length === 0) delete existing.env;
}

if (Object.keys(existing).length === 0) {
  fs.unlinkSync(path);
} else {
  fs.writeFileSync(path, JSON.stringify(existing, null, 2) + '\n');
}
" "$cfg" 2>/dev/null && log "  · .claude/settings.json reverted"
    rmdir "$repo/.claude" 2>/dev/null || true
  fi

  # 5. AGENTS.md — remove only if generated by osEngineer
  if [ -f "$repo/AGENTS.md" ] && grep -q 'osengineer_version:' "$repo/AGENTS.md" 2>/dev/null; then
    rm -f "$repo/AGENTS.md"
    log "  · AGENTS.md removed"
  fi

  # 6. CLAUDE.md — remove osEngineer section only
  if [ -f "$repo/CLAUDE.md" ] && grep -q '## osEngineer' "$repo/CLAUDE.md" 2>/dev/null; then
    local line_count
    line_count="$(wc -l < "$repo/CLAUDE.md" | tr -d ' ')"
    if [ "$line_count" -le 10 ]; then
      rm -f "$repo/CLAUDE.md"
      log "  · CLAUDE.md removed (only osEngineer content)"
    else
      node -e "
const fs = require('fs');
const path = process.argv[1];
const content = fs.readFileSync(path, 'utf8');
const lines = content.split('\n');
let start = -1, end = -1;
for (let i = 0; i < lines.length; i++) {
  if (/^##\\s+osEngineer\\s*\$/.test(lines[i])) { start = i; }
  else if (start !== -1 && /^##\\s+/.test(lines[i])) { end = i; break; }
}
if (start === -1) process.exit(0);
const out = [...lines.slice(0, start), ...lines.slice(end === -1 ? lines.length : end)].join('\n').replace(/\\n{3,}/g, '\\n\\n');
fs.writeFileSync(path, out);
" "$repo/CLAUDE.md" 2>/dev/null && log "  · osEngineer section removed from CLAUDE.md"
    fi
  fi

  # 7. git safe.directory
  git config --global --unset safe.directory "$repo" 2>/dev/null || true
}

# ── Workbench uninstall ────────────────────────────────────────────────────

uninstall_workbench() {
  local root="${1:-$(dirname "$SCRIPT_DIR")}"
  [ -d "$root" ] || { warn "workbench root $root does not exist"; return 0; }

  log "workbench root: $root"

  for repo in "$root"/*; do
    [ -d "$repo/.git" ] || continue
    uninstall_repo "$repo"
  done

  # Workbench-level files
  if [ -f "$root/AGENTS.md" ] && grep -q 'scope: workbench' "$root/AGENTS.md" 2>/dev/null; then
    rm -f "$root/AGENTS.md"
    log "  · workbench AGENTS.md removed"
  fi

  if [ -d "$root/.osengineer" ]; then
    read -r -p "[osEngineer-uninstall] Remove workbench-level .osengineer/? [y/N] " response
    if [[ "$response" =~ ^[Yy]$ ]]; then
      rm -rf "$root/.osengineer"
      log "  · workbench .osengineer/ removed"
    fi
  fi
}

# ── Global hooks uninstall ─────────────────────────────────────────────────

uninstall_global_hooks() {
  log "removing global git hooks"
  local gdir
  gdir="$(git config --global core.hooksPath 2>/dev/null || echo "")"
  if [ -z "$gdir" ]; then
    gdir="$HOME/.git-hooks"
  fi
  if [ -d "$gdir" ]; then
    for hook in commit-msg pre-commit post-commit; do
      local dst="$gdir/$hook"
      if [ -f "$dst" ] && is_osengineer_hook "$dst"; then
        if [ -f "$dst.pre-osengineer" ]; then
          mv "$dst.pre-osengineer" "$dst"
          log "  · restored original global $hook hook"
        else
          rm -f "$dst"
          log "  · removed global $hook hook"
        fi
      fi
    done
  fi

  local current_path
  current_path="$(git config --global core.hooksPath 2>/dev/null || echo "")"
  if [ "$current_path" = "$gdir" ]; then
    read -r -p "[osEngineer-uninstall] Unset global core.hooksPath? [y/N] " response
    if [[ "$response" =~ ^[Yy]$ ]]; then
      git config --global --unset core.hooksPath 2>/dev/null || true
      log "  · core.hooksPath unset"
    fi
  fi
}

# ── Dispatch ───────────────────────────────────────────────────────────────

if [ $# -eq 0 ]; then
  cat <<USAGE
osEngineer uninstaller — version $VERSION

Usage:
  $0 <repo-path>                Remove from a single repo
  $0 --workbench [<path>]       Remove from every .git repo under <path>
  $0 --global                   Remove global git hooks
  $0 --all                      All of the above

USAGE
  exit 1
fi

case "$1" in
  --workbench)
    uninstall_workbench "${2:-}"
    ;;
  --global)
    uninstall_global_hooks
    ;;
  --all)
    uninstall_workbench
    uninstall_global_hooks
    if [ -d "/opt/sovereign-shield" ]; then
      uninstall_repo "/opt/sovereign-shield"
    fi
    ;;
  -h|--help)
    cat <<USAGE
osEngineer uninstaller — version $VERSION
Usage: $0 <repo-path> | --workbench [<path>] | --global | --all
USAGE
    ;;
  *)
    uninstall_repo "$1"
    ;;
esac

log "osEngineer uninstall complete (version $VERSION)"
