#!/usr/bin/env bash
# osEngineer-validate-commit.sh — git commit-msg hook.
#
# Enforces Conventional Commits format on every `git commit` (regardless of
# whether the commit comes from Claude, a manual shell session, an IDE, or
# CI). Triggered by git itself; receives the message file as $1.
#
# Active when the repo has .osengineer/state.yml. No-op otherwise so it can
# safely be installed globally.
#
# Honours OSE_BYPASS=1 (logged to .osengineer/bypass-log.jsonl).
#
# Exits:
#   0 — message accepted (or hook inactive)
#   1 — message rejected (git aborts the commit)

set -uo pipefail

MSG_FILE="${1:-}"
[ -n "$MSG_FILE" ] && [ -f "$MSG_FILE" ] || exit 0

# Active only in osEngineer repos
[ -f .osengineer/state.yml ] || exit 0

# Bypass escape hatch — always logged
if [ "${OSE_BYPASS:-0}" = "1" ]; then
  printf '{"ts":"%s","hook":"validate-commit","reason":"OSE_BYPASS=1"}\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> .osengineer/bypass-log.jsonl 2>/dev/null
  exit 0
fi

SUBJECT=$(head -1 "$MSG_FILE")

# Strip leading whitespace
SUBJECT="${SUBJECT#"${SUBJECT%%[![:space:]]*}"}"

# Skip empty messages (git itself rejects these)
[ -n "$SUBJECT" ] || exit 0

# Allow merge / revert commits (auto-generated by git)
case "$SUBJECT" in
  Merge\ *|Revert\ *|"fixup! "*|"squash! "*) exit 0 ;;
esac

# Conventional Commits format: type(scope): subject
if ! [[ "$SUBJECT" =~ ^(feat|fix|docs|style|refactor|perf|test|build|ci|chore)(\([^\)]+\))?:[[:space:]].+ ]]; then
  cat >&2 <<EOF
[osEngineer] commit rejected: message must follow Conventional Commits.
Format:   <type>(<scope>): <subject>
Types:    feat | fix | docs | style | refactor | perf | test | build | ci | chore
Subject:  imperative mood, lowercase, ≤72 chars, no trailing period.
Got:      $SUBJECT

Bypass with OSE_BYPASS=1 if absolutely necessary.
EOF
  exit 1
fi

if [ ${#SUBJECT} -gt 72 ]; then
  echo "[osEngineer] commit rejected: subject must be 72 chars or less (got ${#SUBJECT})." >&2
  exit 1
fi

exit 0
